### ISSUE TITLE
Sharing a sample scene

### ISSUE THREAD

**Issue by Kulgann** [dreaw131313/MotionMatchingByDreaw#1]
Hey there,
Great work! Would it be at all possible to share a working sample scene so we can get a sense of how the system is supposed to be set up?
Thank you very much.

**Comment by dreaw131313** [comment]
Hi
Thank you! Better idea will be to make to tutorial on youtube, but it will take me some time couse my english is not that good. If you want I can try help you, maybe by Discord. Just let me know here.

**Comment by Kulgann** [comment]
Hi there. Thank you for responding. I would love to connect with you over discord. Do you have a server? I still think that this wonderfull tech should be structured as a proper package. I can help with that too.

**Comment by dreaw131313** [comment]
Here is invitation to discord channel: https://discord.gg/PMhd43tg

**Comment by Kulgann** [comment]
> Here is invitation to discord channel: [discord.gg/PMhd43tg](https://discord.gg/PMhd43tg)

Sadly the invite seems to be invalid

**Comment by dreaw131313** [comment]
This must working: https://discord.gg/yYfyFcHf

**Comment by dreaw131313** [comment]
But if is not working you can send your discord user name on this address: motionmatchingforunity@gmail.com
