### ISSUE TITLE
What Minumum version for Unity?

### ISSUE THREAD

**Issue by ken-tank** [dreaw131313/MotionMatchingByDreaw#7]
i got namespace error (Not Found) on Brust Job Package with unity 2021.3
`The type or namespace name 'IJobParallelForBatch' could not be found`

**Comment by ken-tank** [comment]
For anyone who has same problem,
you need this package installed on your project:

- Brust
- Collections
- Entity Component System (ECS)

ECS was hidden in package manager, you need install it by name 
`com.unity.entities`

**Comment by ItsSaswata** [comment]
> For anyone who has same problem,
> you need this package installed on your project:
> 
> - Brust
> - Collections
> - Entity Component System (ECS)
> 
> ECS was hidden in package manager, you need install it by name 
> `com.unity.entities`

Okay but then what where to start what to do?

**Comment by ken-tank** [comment]
> > For anyone who has same problem,
> > you need this package installed on your project:
> > 
> > * Brust
> > * Collections
> > * Entity Component System (ECS)
> > 
> > ECS was hidden in package manager, you need install it by name
> > `com.unity.entities`
> 
> Okay but then what where to start what to do?

i don't know, how to use this tool
